/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_viral_shen_gtb_GtbProbe */

#ifndef _Included_edu_mit_viral_shen_gtb_GtbProbe
#define _Included_edu_mit_viral_shen_gtb_GtbProbe
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_viral_shen_gtb_GtbProbe_NOPIECE
#define edu_mit_viral_shen_gtb_GtbProbe_NOPIECE 0L
#undef edu_mit_viral_shen_gtb_GtbProbe_PAWN
#define edu_mit_viral_shen_gtb_GtbProbe_PAWN 1L
#undef edu_mit_viral_shen_gtb_GtbProbe_KNIGHT
#define edu_mit_viral_shen_gtb_GtbProbe_KNIGHT 2L
#undef edu_mit_viral_shen_gtb_GtbProbe_BISHOP
#define edu_mit_viral_shen_gtb_GtbProbe_BISHOP 3L
#undef edu_mit_viral_shen_gtb_GtbProbe_ROOK
#define edu_mit_viral_shen_gtb_GtbProbe_ROOK 4L
#undef edu_mit_viral_shen_gtb_GtbProbe_QUEEN
#define edu_mit_viral_shen_gtb_GtbProbe_QUEEN 5L
#undef edu_mit_viral_shen_gtb_GtbProbe_KING
#define edu_mit_viral_shen_gtb_GtbProbe_KING 6L
#undef edu_mit_viral_shen_gtb_GtbProbe_NOSQUARE
#define edu_mit_viral_shen_gtb_GtbProbe_NOSQUARE 64L
#undef edu_mit_viral_shen_gtb_GtbProbe_H1_CASTLE
#define edu_mit_viral_shen_gtb_GtbProbe_H1_CASTLE 8L
#undef edu_mit_viral_shen_gtb_GtbProbe_A1_CASTLE
#define edu_mit_viral_shen_gtb_GtbProbe_A1_CASTLE 4L
#undef edu_mit_viral_shen_gtb_GtbProbe_H8_CASTLE
#define edu_mit_viral_shen_gtb_GtbProbe_H8_CASTLE 2L
#undef edu_mit_viral_shen_gtb_GtbProbe_A8_CASTLE
#define edu_mit_viral_shen_gtb_GtbProbe_A8_CASTLE 1L
#undef edu_mit_viral_shen_gtb_GtbProbe_DRAW
#define edu_mit_viral_shen_gtb_GtbProbe_DRAW 0L
#undef edu_mit_viral_shen_gtb_GtbProbe_WMATE
#define edu_mit_viral_shen_gtb_GtbProbe_WMATE 1L
#undef edu_mit_viral_shen_gtb_GtbProbe_BMATE
#define edu_mit_viral_shen_gtb_GtbProbe_BMATE 2L
#undef edu_mit_viral_shen_gtb_GtbProbe_FORBID
#define edu_mit_viral_shen_gtb_GtbProbe_FORBID 3L
#undef edu_mit_viral_shen_gtb_GtbProbe_UNKNOWN
#define edu_mit_viral_shen_gtb_GtbProbe_UNKNOWN 7L
/*
 * Class:     edu_mit_viral_shen_gtb_GtbProbe
 * Method:    probeHard
 * Signature: (ZII[I[I[B[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_viral_shen_gtb_GtbProbe_probeHard
  (JNIEnv *, jobject, jboolean, jint, jint, jintArray, jintArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     edu_mit_viral_shen_gtb_GtbProbe
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_viral_shen_gtb_GtbProbe_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
